language: sql
variant: mysql
name: mysql
_extends: [base]
types:
  bool: TINYINT(1)
others:
  autoincrement: AUTO_INCREMENT 
  variable: '?'
  field: '{entityAlias}.`{name}`'
  column: '`{name}`'
  from: 'FROM `{name}` {alias} '
  join: 'INNER JOIN `{name}` {alias} ON {relation}'
  false: 'FALSE'
  true: 'TRUE'
functions:
  numeric:
    trunc: 'TRUNCATE({0},{1})'  