version: '3'

networks:
  lambdaorm:
    driver: bridge
services:
  source:
    container_name: lambdaorm-source
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - source:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - lambdaorm
    # command: >

    #   mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "GRANT ALL ON *.* TO 'test'@'%' with grant option; FLUSH PRIVILEGES;"   
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  mysql:
    container_name: lambdaorm-mysql-57
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - lambdaorm
    # command: >

    #   mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "GRANT ALL ON *.* TO 'test'@'%' with grant option; FLUSH PRIVILEGES;"  
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  postgres:
    container_name: lambdaorm-postgres-10
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - lambdaorm
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: lambdaorm-mssql
    environment:
      SA_PASSWORD: "Lambda1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - lambdaorm
    volumes:
      - mssql:/var/opt/mssql
  oracle:
    container_name: lambdaorm-oracle-19
    image: oracledb19c/oracle.19.3.0-ee:oracle19.3.0-ee
    # image: akaronte/oracle:19.3.0.0
    # image: oracledb19c/oracle.19.3.0-ee:oracle19.3.0-ee
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLCPDB
      ORACLE_PWD: 1qazxsw2
      ORACLE_CHARACTERSET: WE8MSWIN1252
    volumes:
      - oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521
      - 5500:5500
      # - 8080:8080
    networks:
      - lambdaorm
  mongodb:
    image: mongo:5.0
    container_name: lambdaorm-mongo
    ports:
      - '27017:27017'
    networks:
      - lambdaorm
    environment:
      - MONGO_INITDB_DATABASE=northwind
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    restart: always
    volumes:
      - mongodb:/data/db
  mariadb:
    container_name: lambdaorm-mariadb-103
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-log:/var/log/mysql
    ports:
      - 3308:3306
    networks:
      - lambdaorm
volumes:
  source: null
  mysql: null
  postgres-data: null
  mariadb-data: null
  mariadb-log: null
  mssql: null
  mongodb: null
  oradata: null
    # volumes:
    #   source:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/source
    #   mysql:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/mysql
    #   postgres-data:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/postgres-data
    #   mariadb-data:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/mariadb-data
    #   mariadb-log:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/mariadb-log
    #   mssql:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/mssql
    #   mongodb:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/mongodb
    #   oradata:
    #     driver: local
    #     driver_opts:
    #       o: bind
    #       type: none
    #       device: ~/volume/oradata
