version: '3'

networks:
  default:
    name: lambdaorm

services:
  source:
    container_name: lambdaorm-source
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - source:/var/lib/mysql
    ports:
      - 3306:3306
    # command: >

    #   mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "GRANT ALL ON *.* TO 'test'@'%' with grant option; FLUSH PRIVILEGES;"   
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  mysql:
    container_name: lambdaorm-mysql-57
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3307:3306'
    # command: >

    #   mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "GRANT ALL ON *.* TO 'test'@'%' with grant option; FLUSH PRIVILEGES;"  
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  postgres:
    container_name: lambdaorm-postgres-10
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    container_name: "lambdaorm-mssql"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Lambda1234!"
      ACCEPT_EULA: "Y"
    # volumes:
    #   - mssql:/var/opt/mssql
  mongodb:
    image: "mongo:3.4.18"
    container_name: lambdaorm-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
  mariadb:
    container_name: lambdaorm-mariadb-103
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-log:/var/log/mysql
    ports:
      - 3308:3306
volumes:
  source: null
  mysql: null
  postgres: null
  mariadb-data: null
  mariadb-log: null
  mssql: null
  mongodb: null
  oracle: null
