version: '3'
networks:
  data:
    driver: bridge
services:  
  postgres:
    container_name: postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=countries
      - POSTGRES_USER=countries
      - POSTGRES_PASSWORD=countries
    ports:
      - '5432:5432'
    expose:
      - 5432  
    networks:
      - data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "countries" ]
      interval: 3s
      timeout: 1s
      retries: 10
volumes:
  postgres-data:          
