_extends: [sql]
types:
  datetime: TIMESTAMP
ddl:
  incrementalColumDefine: '{name} serial'
  dropPk: 'DROP CONSTRAINT {name}'
  dropUk: 'DROP CONSTRAINT {name}'
  dropFk: 'DROP CONSTRAINT {name}'
  dropIndex: 'DROP INDEX {name}'
dml:
  page: OFFSET {offset} LIMIT {records} 
  insert: INSERT INTO {name}({fields}) VALUES({values}) RETURNING {autoincrementField} AS id
  bulkInsert: INSERT INTO {name}({fields}) VALUES 
others:
  variable: '${number}'