schemasPath: orm/schemas
statePath: orm/state
databases:
  - name: source
    schema: northwind:0.0.2
    dialect: mysql
    connectionSource: env
    connection: ORM_CNN_1
  - name: mysql
    schema: northwind:0.0.2
    dialect: mysql
    connectionSource: direct
    connection:
      host: '0.0.0.0'
      port: 3307
      user: root
      password: root
      database: northwind    
  - name: mariadb    
    schema: northwind:0.0.2
    dialect: mariadb
    connectionSource: env
    connection: ORM_CNN_3
  - name: postgres    
    schema: northwind:0.0.2
    dialect: postgres
    connectionSource: env
    connection: ORM_CNN_4  

# environment variables 
# ORM_CNN_1= {"host":"0.0.0.0","port":3306,"user":"root","password":"root","database":"northwind"}
# ORM_CNN_2= {"host":"0.0.0.0","port":3307,"user":"root","password":"root","database":"northwind"}
# ORM_CNN_3= {"host":"0.0.0.0","port":3308,"user":"root","password":"root","database":"northwind"}
# ORM_CNN_4= {"host":"0.0.0.0","port":5432,"user":"admin","password":"admin","database":"northwind"}      