_extends: [sql]
types:
  boolean: BIT
ddl:
  createPk: "PRIMARY KEY ({columns})"
  incrementalColumDefine: "{name} {type} {nullable} IDENTITY (1, 1)"
dml:
  update: UPDATE {alias} SET {assings} FROM {name} {alias}
  delete: DELETE FROM {name} {alias}
  bulkInsert: INSERT INTO {name}({fields})
others:
  delimiter: "[{name}]"
  sepatatorSql: ' \nGO'
  variable: "@{name}"
