_extends: [sql]
types:
  boolean: BIT
ddl:
  createPk: "PRIMARY KEY ({columns})"
  incrementalColumDefine: "{name} {type} {nullable} IDENTITY (1, 1)"
  dropPk: "DROP CONSTRAINT {name}"
  dropUk: "DROP CONSTRAINT {name}"
  dropFk: "DROP CONSTRAINT {name}"
  dropIndex: "DROP INDEX {name} ON {table}"
dml:
  insert: INSERT INTO {name}({fields}) OUTPUT INSERTED.{autoincrementField} VALUES({values})
  update: UPDATE {alias} SET {assings} FROM {name} {alias}
  delete: DELETE FROM {name} {alias}
  bulkInsert: INSERT INTO {name}({fields})
others:
  delimiter: "[{name}]"
  sepatatorSql: ' \nGO'
  variable: "@{name}"
  false: 0
  true: 1
