_extends: [sql]
types:
  boolean: CHAR(1)
  integer: LONG
  string: VARCHAR2({0})
  datetime: TIMESTAMP
others:
  false: "N"
  true: "Y"
ddl:
  dropPk: "DROP CONSTRAINT {name}"
  dropUk: "DROP CONSTRAINT {name}"
  dropFk: "DROP CONSTRAINT {name}"
  dropIndex: "DROP INDEX {name} ON {table}"
