_extends: [dialects.MySQL]
support:
  sequences: false
  tablespaces: false
  partitions: false
  pkTablespaces: false
  ukTablespaces: false 
ddl:
  objects: null
  tables: null
  views: null
  primaryKeys: null
  uniqueKeys: null
  foreignKeys: null
  indexes: null
  sequences: null
