entities:
  - name: CapEntries
    primaryKey: ["id"]
    uniqueKey: []
    properties:
      - name: id
      - name: processId
      - name: referenceNumber
      - name: currency
      - name: amount
        type: decimal
      - name: entryDate
        type: dateTime
      - name: status
      - name: transactionType
        type: any
      - name: creditorAccount
        type: any
  - name: OmniBoxes
    primaryKey: ["id"]
    uniqueKey: []
    properties:
      - name: id
      - name: category
      - name: data
      - name: keywords                  
sources:
  - name: collectionsMng
    dialect: MongoDB
    mapping: default
    connection: ${CNN_COLLECTION_MNG}   
  - name: insight
    dialect: MongoDB
    mapping: default
    connection: ${CNN_INSIGHT}       
mappings:
  - name: default
    entities:
      - name: CapEntries
        mapping: capEntries
      - name: OmniBoxes
        mapping: omnibox                  
stages:
  - name: default
    sources:
      - name: collectionsMng
        condition: entity=="CapEntries"
      - name: insight
        condition: entity=="OmniBoxes"  
