version: '3'
services:
  mysql:
    container_name: countries-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=countries
      - MYSQL_USER=countries
      - MYSQL_PASSWORD=countries
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3309:3306
  postgres:
    container_name: countries-postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=countries
      - POSTGRES_USER=countries
      - POSTGRES_PASSWORD=countries
    ports:
      - '5434:5432'
