version: '3'

networks:
  northwind:
    driver: bridge
services:  
  MySQL:
    container_name: northwind-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=northwind
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
      - mysql-log:/var/log/mysql
    ports:
      - '3307:3306'
    networks:
      - northwind
    # command: >
    #   mysql --host 127.0.0.1 --port 3306 -uroot -proot -e "GRANT ALL ON *.* TO 'test'@'%' with grant option; FLUSH PRIVILEGES;"  
    healthcheck:
      test: [ "CMD", "mysqladmin", "-uroot", "-proot", "status" ]
      interval: 3s
      timeout: 1s
      retries: 10
  Postgres:
    container_name: northwind-postgres
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_DB=northwind
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - northwind
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "test" ]
      interval: 3s
      timeout: 1s
      retries: 10
  SqlServer:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: northwind-sqlserver
    environment:
      SA_PASSWORD: "Lambda1234!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - northwind
    volumes:
      - sqlserver:/var/opt/mssql
  Oracle:
    container_name: northwind-oracle
    # image: oracledb19c/oracle.19.3.0-ee:oracle19.3.0-ee
    image: akaronte/oracle:19.3.0.0
    environment:
      SVC_HOST: db19c-oracle-db
      SVC_PORT: '1521'
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: ORACLE123
      ORACLE_CHARACTERSET: AL32UTF8
      # ORACLE_EDITION: enterprise
      ENABLE_ARCHIVELOG: 'false'
    volumes:
      # - ./volume/oradata:/opt/oracle/oradata # persistent oracle database data
      #  al usar el volume ./volume/oradata da error de permisos y no crea la instancia dentro del container
      #  por este motivo se crea el volume oradata:
      # info: https://github.com/oracle/docker-images/issues/439
      - oracle_oradata:/opt/oracle/oradata # persistent oracle database data      
      - ./oracle:/home/oracle/setup/custom_scripts
    ports:
      - 1521:1521
      - 5500:5500
      # - 8080:8080
    networks:
      - northwind  
volumes:
  mysql-data:
  mysql-log:
  postgres-data:
  sqlserver:
  oracle_oradata:

