entities:
  - name: Countries
    primaryKey: ["iso3"]
    uniqueKey: ["name"]
    properties:
      - name: name
        required: true
      - name: iso3
        length: 3
        required: true
    relations:
      - name: states
        type: manyToOne
        composite: true
        from: iso3
        entity: States
        to: countryCode
  - name: States
    primaryKey: ["id"]
    uniqueKey: ["countryCode", "name"]
    properties:
      - name: id
        type: integer
        required: true
      - name: name
        required: true
      - name: countryCode
        required: true
        length: 3
    relations:
      - name: country
        from: countryCode
        entity: Countries
        to: iso3
sources:
  - name: dataSource1
    dialect: mysql
    connection:
      host: localhost
      port: 3306
      user: test
      password: test
      database: test
  - name: dataSource2
    dialect: postgres
    connection:
      host: localhost
      port: 5432
      user: test
      password: test
      database: test
stages:
  - name: stage1
    sources:
      - name: dataSource1
        condition: entity == "Countries"
      - name: dataSource2
        condition: entity == "States"
