name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      # install Node.js
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install -g grunt-cli
      - run: npm install
      - name: Lint
        run: npm run lint
      # set up git since we will later push to the repo
      - run: git config --global user.name "FlavioLionelRita"
      - run: git config --global user.email "flaviolrita@gmail.com"
      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
      # upgrade npm version in package.json to the tag used in the release.
      - run: npm version ${{ github.event.release.tag_name }}
      # build the project
      - name: Build
        run: npm run build
      # run tests just in case
      - name: Unit Tests
        run: npm run unit-test
      # publish to NPM -> there is one caveat, continue reading for the fix
      - run: npm publish --tag ${{ github.event.release.target_commitish }}
        env:
          # Use a token to publish to NPM. See below for how to set it up
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # push the version changes to GitHub
      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GH_TOKEN }}
# https://dev.to/savchenko91/auto-publish-npm-package-with-github-actions-57jh
